port:             4567
api_key:
secret_key:
tokens_file:      tokens
default_phone:
default_url:      http://developer.att.com
default_alert:    This is a sample WAP Push message. 
FQDN:             https://api.att.com
